# For info on getting the latest rdme version and obtaining your API_DEFINITION_ID,
# see our docs: https://docs.readme.com/docs/rdme#example-syncing-an-openapi-definition
name: Sync OAS to ReadMe
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: readmeio/rdme@7.3.0
        with:
          rdme: openapi openapi-test-doc --key=rdme_xn8s9he9af700bd9cfc798237bc8c6df42209d43267a8d0693aa6821c45e9c0a68e54f --id=API_DEFINITION_ID